/*
 * JrxmlEditorToolbar.java
 *
 * Created on 23 ottobre 2007, 16.57
 */

package com.jaspersoft.ireport.designer.tools;

import com.jaspersoft.ireport.designer.menu.OpenQueryDialogAction;
import com.jaspersoft.ireport.designer.menu.ZoomInAction;
import com.jaspersoft.ireport.designer.menu.ZoomOutAction;
import org.openide.util.actions.SystemAction;

/**
 *
 * @author  gtoffoli
 */
public class JrxmlEditorToolbar extends javax.swing.JPanel {
    
    /** Creates new form JrxmlEditorToolbar */
    public JrxmlEditorToolbar() {
        initComponents();
        jToolBar1.add( SystemAction.get(OpenQueryDialogAction.class) );
        jToolBar1.add( SystemAction.get(ZoomInAction.class) );
        jToolBar1.add( SystemAction.get(ZoomOutAction.class) );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
