/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SectionPanel.java
 *
 * Created on 22-mar-2009, 1.38.02
 */

package com.jaspersoft.ireport.designer.welcome;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.JComponent;
import javax.swing.UIManager;

/**
 *
 * @author gtoffoli
 */
public class SectionPanel extends javax.swing.JPanel {

    public void setTitle(String title)
    {
        jLabel1.setText(title);
    }

    /** Creates new form SectionPanel */
    public SectionPanel(String title, JComponent content) {
        initComponents();
        add(content, BorderLayout.CENTER);
        setTitle(title);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new TitleLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(SectionPanel.class, "SectionPanel.jLabel1.text")); // NOI18N
        add(jLabel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
